import { jsPDF } from "jspdf";
import type { Feature, Polygon } from "geojson";
import type { ParcelProperties } from "../data/parcels";
import type { Owner } from "../data/owners";
import type { SavedProject } from "../types/project";
import { getOverviewImageUrl, getParcelImageUrl, fetchImageAsBase64 } from "./mapboxStaticImage";

interface ParcelData {
  parcel: Feature<Polygon, ParcelProperties>;
  owner: Owner | null;
  selectionOrder: number;
}

interface ReportProgress {
  current: number;
  total: number;
  status: string;
}

type ProgressCallback = (progress: ReportProgress) => void;

/**
 * Format acres from square meters
 */
function formatAcres(sqmt: number | undefined): string {
  if (!sqmt || isNaN(sqmt)) return "N/A";
  const acres = sqmt / 4046.86;
  if (acres >= 10) return `${acres.toFixed(1)} acres`;
  if (acres >= 1) return `${acres.toFixed(2)} acres`;
  return `${acres.toFixed(3)} acres`;
}

/**
 * Format date for display
 */
function formatDate(date: Date): string {
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

/**
 * Add page header to PDF
 */
function addPageHeader(doc: jsPDF, projectName: string, pageNumber: number, totalPages: number) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Header line
  doc.setDrawColor(100, 100, 100);
  doc.setLineWidth(0.5);
  doc.line(15, 15, pageWidth - 15, 15);

  // Header text
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(projectName, 15, 12);
  doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - 15, 12, { align: "right" });

  // Footer line
  doc.line(15, pageHeight - 15, pageWidth - 15, pageHeight - 15);
  doc.text("Generated by Land Mapping Web", 15, pageHeight - 10);
  doc.text(formatDate(new Date()), pageWidth - 15, pageHeight - 10, { align: "right" });
}

/**
 * Add overview page (Page 1)
 */
async function addOverviewPage(
  doc: jsPDF,
  project: SavedProject,
  parcels: ParcelData[],
  totalPages: number,
  onProgress?: ProgressCallback
): Promise<void> {
  const pageWidth = doc.internal.pageSize.getWidth();
  
  onProgress?.({ current: 0, total: totalPages, status: "Generating overview..." });

  addPageHeader(doc, project.name, 1, totalPages);

  // Title
  doc.setFontSize(24);
  doc.setTextColor(30, 41, 59); // slate-800
  doc.text(project.name, pageWidth / 2, 35, { align: "center" });

  // Subtitle
  doc.setFontSize(14);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text("Parcel Report", pageWidth / 2, 45, { align: "center" });

  // Date
  doc.setFontSize(10);
  doc.text(`Generated: ${formatDate(new Date())}`, pageWidth / 2, 55, { align: "center" });

  // Summary stats
  const totalAcres = parcels.reduce((sum, p) => {
    const sqmt = p.parcel.properties?.SIZE_SQMT;
    return sum + (sqmt && !isNaN(sqmt) ? sqmt / 4046.86 : 0);
  }, 0);

  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text(`Total Parcels: ${parcels.length}`, 15, 70);
  doc.text(`Total Area: ${totalAcres.toFixed(2)} acres`, 15, 78);

  // Overview map image
  try {
    const parcelFeatures = parcels.map(p => p.parcel);
    const imageUrl = getOverviewImageUrl(parcelFeatures, 800, 500);
    
    if (imageUrl) {
      const imageData = await fetchImageAsBase64(imageUrl);
      
      // Add image centered on page
      const imgWidth = pageWidth - 30;
      const imgHeight = (imgWidth * 500) / 800;
      const imgX = 15;
      const imgY = 90;
      
      doc.addImage(imageData, "PNG", imgX, imgY, imgWidth, imgHeight);

      // Add border around image
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.5);
      doc.rect(imgX, imgY, imgWidth, imgHeight);
    }
  } catch (error) {
    console.error("Failed to add overview image:", error);
    doc.setTextColor(200, 100, 100);
    doc.text("(Map image unavailable)", pageWidth / 2, 150, { align: "center" });
  }

  // Parcel summary list
  const listStartY = 210;
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  doc.text("Parcels in this report:", 15, listStartY);

  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105); // slate-600
  
  let y = listStartY + 8;
  for (const parcelData of parcels) {
    const { parcel, owner, selectionOrder } = parcelData;
    const pid = parcel.properties?.PID || "Unknown";
    const ownerName = owner?.ownerName || "Unknown";
    
    if (y > 270) {
      doc.text("...", 20, y);
      break;
    }
    
    doc.text(`${selectionOrder}. ${pid} - ${ownerName}`, 20, y);
    y += 6;
  }
}

/**
 * Add individual parcel page
 */
async function addParcelPage(
  doc: jsPDF,
  parcelData: ParcelData,
  projectName: string,
  pageNumber: number,
  totalPages: number,
  addressLookup?: Map<string, { fullAddress?: string; community?: string }>,
  onProgress?: ProgressCallback
): Promise<void> {
  const { parcel, owner, selectionOrder } = parcelData;
  const pageWidth = doc.internal.pageSize.getWidth();
  const props = parcel.properties;

  onProgress?.({ 
    current: pageNumber - 1, 
    total: totalPages, 
    status: `Processing parcel ${selectionOrder}...` 
  });

  doc.addPage();
  addPageHeader(doc, projectName, pageNumber, totalPages);

  // Parcel number badge
  doc.setFillColor(6, 182, 212); // cyan-500
  doc.circle(25, 32, 8, "F");
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text(String(selectionOrder), 25, 35, { align: "center" });

  // Parcel title
  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);
  doc.text(`Parcel ${props?.PID || "Unknown"}`, 40, 35);

  // Parcel map image
  try {
    const imageUrl = getParcelImageUrl(parcel, 700, 350);
    
    if (imageUrl) {
      const imageData = await fetchImageAsBase64(imageUrl);
      
      const imgWidth = pageWidth - 30;
      const imgHeight = (imgWidth * 350) / 700;
      const imgX = 15;
      const imgY = 45;
      
      doc.addImage(imageData, "PNG", imgX, imgY, imgWidth, imgHeight);

      // Border
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.5);
      doc.rect(imgX, imgY, imgWidth, imgHeight);
    }
  } catch (error) {
    console.error("Failed to add parcel image:", error);
  }

  // Details section
  const detailsY = 145;
  
  doc.setFillColor(241, 245, 249); // slate-100
  doc.rect(15, detailsY, pageWidth - 30, 80, "F");
  
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text("Parcel Details", 20, detailsY + 10);
  
  doc.setDrawColor(200, 200, 200);
  doc.line(20, detailsY + 14, pageWidth - 20, detailsY + 14);

  // Detail rows
  const details = [
    ["PID:", props?.PID || "—"],
    ["Owner:", owner?.ownerName || "Unknown"],
    ["LV Number:", props?.LV_NUMBER || "—"],
    ["Volume/Folio:", props?.VOL_FOL || "—"],
    ["Size:", formatAcres(props?.SIZE_SQMT)],
  ];

  // Try to get address from lookup
  if (addressLookup && props?.LV_NUMBER) {
    const address = addressLookup.get(props.LV_NUMBER);
    if (address?.fullAddress) {
      details.push(["Address:", address.fullAddress]);
    }
  }

  doc.setFontSize(10);
  let detailY = detailsY + 24;
  const labelX = 20;
  const valueX = 60;

  for (const [label, value] of details) {
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(label, labelX, detailY);
    doc.setTextColor(30, 41, 59);
    
    // Truncate long values
    const maxWidth = pageWidth - valueX - 20;
    const truncatedValue = doc.splitTextToSize(value, maxWidth)[0] || value;
    doc.text(truncatedValue, valueX, detailY);
    
    detailY += 10;
  }
}

/**
 * Generate PDF report for a project
 */
export async function generateProjectReport(
  project: SavedProject,
  parcelsData: ParcelData[],
  addressLookup?: Map<string, { fullAddress?: string; community?: string }>,
  onProgress?: ProgressCallback
): Promise<Blob> {
  // Sort parcels by selection order
  const sortedParcels = [...parcelsData].sort((a, b) => a.selectionOrder - b.selectionOrder);
  
  const totalPages = 1 + sortedParcels.length; // Overview + one per parcel
  
  // Create PDF (A4 size)
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // Add overview page
  await addOverviewPage(doc, project, sortedParcels, totalPages, onProgress);

  // Add individual parcel pages
  for (let i = 0; i < sortedParcels.length; i++) {
    await addParcelPage(
      doc,
      sortedParcels[i],
      project.name,
      i + 2, // Page 2 onwards
      totalPages,
      addressLookup,
      onProgress
    );
  }

  onProgress?.({ current: totalPages, total: totalPages, status: "Complete!" });

  // Return as blob
  return doc.output("blob");
}

/**
 * Download the PDF report
 */
export function downloadReport(blob: Blob, projectName: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${projectName} parcel report.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
